In [1]:
import numpy as np
import theano
import theano.tensor as T

In [58]:
x = np.asarray(np.random.rand(5,5), dtype = 'float32')
s = np.asarray(0.1, dtype = 'float32')
n = 3

In [59]:
state = theano.shared(x)
step = theano.shared(s)
n_bits = theano.shared(n)
fixed_updates = []
precision = T.pow(2,n_bits-1)-1
fixed = T.cast(T.maximum(T.minimum(T.round(state / step), precision), -precision) * step, dtype = 'float32')

fixed_updates.append((state, fixed))
print(fixed_updates)

[(<TensorType(float32, matrix)>, Elemwise{Cast{float32}}.0)]


In [60]:
func1 = theano.function(inputs = [], outputs = [], updates = fixed_updates)

In [61]:
print(state.get_value())
#func1()
print(state.get_value())

[[ 0.21376927  0.58785957  0.61557835  0.53088105  0.0928635 ]
 [ 0.4422904   0.76952213  0.23917456  0.06451438  0.86683255]
 [ 0.10539833  0.9703179   0.92030901  0.06155436  0.55277675]
 [ 0.47443894  0.99992239  0.45073289  0.2415255   0.22808978]
 [ 0.26661342  0.14108357  0.4408094   0.55407232  0.16239165]]
[[ 0.21376927  0.58785957  0.61557835  0.53088105  0.0928635 ]
 [ 0.4422904   0.76952213  0.23917456  0.06451438  0.86683255]
 [ 0.10539833  0.9703179   0.92030901  0.06155436  0.55277675]
 [ 0.47443894  0.99992239  0.45073289  0.2415255   0.22808978]
 [ 0.26661342  0.14108357  0.4408094   0.55407232  0.16239165]]


In [62]:
def quantize(input, step_size, n_bits):
    p = T.pow(2,n_bits-1)-1
    return T.cast(T.maximum(T.minimum(T.round(input / step), p), -p) * step_size, dtype = 'float32')

In [63]:
new_updates = []
new_updates.append((state, quantize(state, step, n_bits)))

In [64]:
func2 = theano.function(inputs = [], outputs = [], updates = new_updates)

In [65]:
print(state.get_value())
func2()
print(state.get_value())

[[ 0.21376927  0.58785957  0.61557835  0.53088105  0.0928635 ]
 [ 0.4422904   0.76952213  0.23917456  0.06451438  0.86683255]
 [ 0.10539833  0.9703179   0.92030901  0.06155436  0.55277675]
 [ 0.47443894  0.99992239  0.45073289  0.2415255   0.22808978]
 [ 0.26661342  0.14108357  0.4408094   0.55407232  0.16239165]]
[[ 0.2         0.30000001  0.30000001  0.30000001  0.1       ]
 [ 0.30000001  0.30000001  0.2         0.1         0.30000001]
 [ 0.1         0.30000001  0.30000001  0.1         0.30000001]
 [ 0.30000001  0.30000001  0.30000001  0.2         0.2       ]
 [ 0.30000001  0.1         0.30000001  0.30000001  0.2       ]]


In [37]:
pp = 'a;ldkgja;lgkalkgj'
if pp:
    print(1)
else:
    print(0)

1


In [66]:
a = np.asarray([[1,2,3,4],[2,3,4,5],[1,-1,1,-1]], dtype = 'float32')

In [72]:
print(a)
print(np.sum(a,axis = (0)))

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 1. -1.  1. -1.]]
[ 4.  4.  8.  8.]


In [71]:
b = np.asarray([1,2,3,4], dtype = 'float32')
c = np.asarray([1,2,3,4], dtype = 'float32')
print(b / c)

[ 1.  1.  1.  1.]


In [75]:
def foo(a):
    a.set_x(10)
    return 0


In [76]:
class testc(object):
    def __init__(self):
        self.x = 5
    
    def set_x(self, a):
        self.x = a
        

kkk = testc()
print(kkk.x)

foo(kkk)
print(kkk.x)







5
10
